# Database - local PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/assignmentmanager
spring.datasource.username=adi
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

#Remove at the earliest
spring.flyway.repair-on-migrate=true

# Auth - local dev values
app.auth.google.client-ids=${GOOGLE_CLIENT_IDS}
app.auth.google.web-client-id=${GOOGLE_WEB_CLIENT_ID}
app.auth.google.android-client-id=${GOOGLE_ANDROID_CLIENT_ID}
app.auth.jwt.secret=${JWT_SECRET}
app.auth.google.client-secret=${GOOGLE_CLIENT_SECRET}
app.auth.jwt.ttl-seconds=43200
app.auth.google.redirect-uri=http://localhost:8080/auth/google/callback
